name: Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd polybot
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/polybot:latest .
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/polybot:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Describe Polybot Instances
        run: |
          POLYBOT_INSTANCES=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=PolybotInstance" --query 'Reservations[*].Instances[*].InstanceId' --output text)
          echo "Polybot Instances: $POLYBOT_INSTANCES"
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
