name: Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Build and push image
        run: |
          cd polybot
          
          docker build -t polybot-v1.0.0 .
          docker tag  polybot-v1.0.0 davidhei/aws-polybotservice:polybot-v1.0.0
          docker push davidhei/aws-polybotservice:polybot-v1.0.0

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Deploy new version
        run: |         
          
          docker run --name polybot --restart always -p 8443:8443 davidhei/aws-polybotservice:polybot-v1.0.0    
     
