name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4

      - name: Build and push image
        run: |
          cd yolo5
          
          docker build -t yolo5-v1.0.0 .
          docker tag yolo5-v1.0.0 davidhei/aws-polybotservice:yolo5-v1.0.0
          docker push davidhei/aws-polybotservice:yolo5-v1.0.0

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v4
      - name: Deploy new version
        run: |   
          
          docker run -p 80:80 --name yolo5 davidhei/aws-polybotservice:yolo5-v1.0.0  
