name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd yolo5
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest

  Deploy:
    runs-on: ubuntu-latest
    needs:
      - Build

    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Deploy new version
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          LOAD_BALANCER_DNS: ${{ secrets.LOAD_BALANCER_DNS }}
        run: |
          ssh -o StrictHostKeyChecking=no -i "$SSH_PRIVATE_KEY" "$SSH_USER@$LOAD_BALANCER_DNS" << EOF
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest
            docker stop yolo5 || true
            docker rm yolo5 || true
            docker run -d --restart always --name yolo5 -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest
            EOF
