name: Yolo5 Microservice Deployment

on:
  push:
    paths:
      - 'yolo5/**'
    branches:
      - main

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        run: |
          cd yolo5
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest .
          echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Deploy new version
        run: |
          ssh -o StrictHostKeyChecking=no -i /path/to/your/private/key.pem ${{ secrets.SSH_USER }}@${{ secrets.LOAD_BALANCER_DNS }} << 'EOF'
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest
          docker stop yolo5_container || true
          docker rm yolo5_container || true
          docker run -d --restart always --name yolo5_container -p 8443:8443 ${{ secrets.DOCKER_HUB_USERNAME }}/yolo5:latest
          EOF
